name: Test

on:
  push:
  workflow_dispatch:

jobs:
  Test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - 8.1

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Validate composer.json
        run: composer validate

      - name: Cache dependencies
        id: composer-cache
        uses: actions/cache@v2
        with:
          path: vendor
          key: php-${{ matrix.php }}-${{ hashFiles('composer.json') }}
          restore-keys: php-${{ matrix.php }}-

      - name: Install dependencies
        run: composer update --no-interaction --no-progress

      - name: Run test suite
        run: sudo composer --no-plugins test
